### ISSUE TITLE
download data not working?

### ISSUE THREAD

**Issue by gweinberg** [isle-project/isle-editor#1220]
On any ISLE data explorer (on Firefox 79.0, on Win10, Dell XPS-13), when I click to download data -> select "save as CSV", nothing happens.  I don't get any dialog box asking where to save anything; I don't get any notification that anything has saved; and I don't get any "download" progress indicator on the browser.

**Comment by Planeshifter** [comment]
This should have been fixed meanwhile. Can you point me please to one data explorer where the download is not working? I will then re-upload it for us to check whether the problem went away.

**Comment by gweinberg** [comment]
Thanks; for instance: https://isle.stat.cmu.edu/36-200-summer20-2/worldcup_project2/

**Comment by Planeshifter** [comment]
Thanks. Can reproduce the error. I will look into it today, assuming that it will be easy to fix.

**Comment by Planeshifter** [comment]
The bug is now fixed per e698b53882c4f60b6498ea9eec2ed7b8efb438e4 and the fix will be included in the next release. Thanks again for reporting it!

**Comment by gweinberg** [comment]
Thanks.  So, I have the latest version of the editor (I like the new "an updated version is available" button); and I saw I was able to download the data on the new lab last week, but with the latest version, I loaded another copy of "worldcup" (at https://isle.stat.cmu.edu/36-200-summer20-2/worldcup_new_version/ ), but I still can't download the data on it.

**Comment by Planeshifter** [comment]
Yeah, that makes sense given that the next release is not out. The plan is to have a new version out by the end of this weekend.

**Comment by gweinberg** [comment]
Ah!  Ok thanks.
